### ISSUE TITLE
Style selection problem

### ISSUE THREAD

**Issue by KenavR** [DevvitIO/ReallyAnnoyingDirectory#35]
If you select the same style a couple of times it doesn't load any CSS file.

Tor Edit: [Gif 1](https://gyazo.com/b75b2e371567117ad4da7e1e5c47d3f8 )  [Gif 2](https://gyazo.com/76166115729f0eeaf50513ee9233fb05 )

Tor Edit2:Created new issue #53  for suggestion

**Comment by rowhitswami** [comment]
I'd like to take this one.

**Comment by Tor020** [comment]
Created two gifs to help demonstrate and clarify the problem. Also removed suggestion and created new Issue for it

**Comment by Tor020** [comment]
There's still a bug with the style selection button. If you select the stylesheet that's already selected, it will break the page. Alternatively, switching to the default stylesheet and then to a different one will sometimes break the page as well. 

I suggest adding functionality to disable the currently selected stylesheet from the dropdown list to help make the problem simpler
