### ISSUE TITLE
Incorrect URL in 'Back to directory' link within subPages

### ISSUE THREAD

**Issue by Tor020** [DevvitIO/ReallyAnnoyingDirectory#39]
This bug involves all of the subPages within the subDirectory. The link that is required in the template, ie: the link back to the directory root page needs to be updated. The details are below

Fixing this involves going into everyones subDirectory page. and changing absolutely nothing except for 
**href="https://github.com/LearnDevelopmentPublic/ReallyAnnoyingDirectory"**

to be

**href="https://devvit.io/ReallyAnnoyingDirectory/"**

**Comment by mgnc2867** [comment]
I'll take this on 😊
