### ISSUE TITLE
Create transitioning effect for stylesheets on load.

### ISSUE THREAD

**Issue by Tor020** [DevvitIO/ReallyAnnoyingDirectory#53]
Kenavr from issue#35: Set the opacity of the page to 0 until a stylesheet is loaded and then soft transition to opacity: 1.

This would remove the visible style change on page load.

**Comment by kevPo** [comment]
Mind if I take a crack at this?

**Comment by Tor020** [comment]
https://github.com/DevvitIO/ReallyAnnoyingDirectory#q-can-i-work-on-this-issue

**Comment by kevPo** [comment]
Looks like it's taken care of...
